

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.test]
install_crate = "nextest"
command = "cargo"
args = ["nextest", "run", "--no-tests=pass"]

[tasks.check]
dependencies = ["fmt", "clippy", "test"]

[tasks.clippy-fix]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]
